CS3620_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as userViews
from django.contrib.auth import login, views as authenticationViews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('hobbies/', include('hobby.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('contact/', include('contact.urls')),
    path('register/', userViews.register, name='Register'),
    path('login/',authenticationViews.LoginView.as_view(template_name = 'users/login.html'), name='Login'),
    path('logout/',authenticationViews.LogoutView.as_view(template_name = 'users/logout.html'), name='Logout'),

]

contact/urls.py
from . import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
]

hobby/urls.py
from . import views
from django.urls import path

app_name = 'hobby'

urlpatterns = [
    #/hobbies/
    path('', views.index, name='index'),
    #/hobbies/1
    path('<int:hobbyId>', views.detail, name='detail'),
]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/urls.py
from . import views
from django.urls import path

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:projectId>', views.detail, name='detail'),
    path('add', views.createProj, name='createProj'),
    path('update/<int:projectId>', views.updateProj, name='updateProj'),
    path('delete/<int:projectId>', views.deleteProj, name='deleteProj'),
]

contact/models.py
from django.db import models

# Create your models here.
class ContactMsg(models.Model):
    def __str__(self):
        return self.hobby_name

    msg_author = models.CharField(max_length=200)
    msg_email = models.EmailField(max_length=200)
    msg_message = models.TextField(max_length=600)

hobby/models.py
from django.db import models

# Create your models here.
class Hobby(models.Model):

    def __str__(self):
        return self.hobby_name

    hobby_name = models.CharField(max_length=200)
    hobby_desc = models.CharField(max_length=300)
    hobby_img = models.CharField(max_length=500, default = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Question_Mark.svg/1200px-Question_Mark.svg.png')

    

home/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):

    def __str__(self):
        return self.proj_name

    proj_name = models.CharField(max_length=200)
    proj_desc = models.CharField(max_length=200)
    proj_img = models.CharField(max_length=500, default='https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Question_Mark.svg/1200px-Question_Mark.svg.png')

users/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms
from .models import ContactMsg

class ContactMsg(forms.ModelForm):
    class Meta:
        model = ContactMsg
        fields = ['msg_author', 'msg_email', 'msg_message']

portfolio/forms.py
from django import forms
from .models import Project

class projForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['proj_name', 'proj_desc', 'proj_img']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [ 'email', 'username', 'password1', 'password2']

contact/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import ContactMsg

# Create your views here.
def index(request):
    
    form = ContactMsg(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('contact:index')
    
    return render(request, 'contact/index.html', {'form': form})

hobby/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Hobby
from django.template import loader

# Create your views here.
def index(request):
    hobbyList = Hobby.objects.all()
    context = {
        'hobbyList': hobbyList,
    }
    return render(request, 'hobby/index.html', context)

def detail(request, hobbyId):
    hobby = Hobby.objects.get(pk=hobbyId)
    context = {
        'hobby': hobby
    }
    return render(request, 'hobby/detail.html', context)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

# Create your views here.
def index(request):
    aboutMe = ('Hello! I am Alex Klein, a current Senior at Weber State but this will be my last semester at ' 
            'Weber as I am transferring to UGA in the Spring to finish out my degree.\n I am interested in '
                        'Full Stack Web Development but I am not comfortable enough in any specific framework to work '
                        'on anything real at this time. I\'m pretty lost at what it is exactly I want to do, which '
                        'isn\'t a good look for a senior. But this is what I get for rushing through without thinking...')
    context = {'aboutMe':aboutMe}
    return render(request, 'home/index.html', context)

portfolio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from portfolio.forms import projForm
from .models import Project
from django.template import loader

# Create your views here.
def index(request):
    projList = Project.objects.all()
    context = {
        'projList': projList,
    }
    return render(request, 'project/index.html', context)

def detail(request, projectId):
    project = Project.objects.get(pk=projectId)
    context = {
        'project': project
    }
    return render(request, 'project/detail.html', context)

@login_required
def createProj(request):
    form = projForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('portfolio:index')
    
    return render(request, 'project/projForm.html', {'form': form})

@login_required
def updateProj(request, projectId):
    project = Project.objects.get(id=projectId)
    form = projForm(request.POST or None, instance=project)

    if form.is_valid():
        form.save()
        return redirect('portfolio:index')

    return render(request, 'project/projForm.html', {'form': form, 'project': project})

@login_required
def deleteProj(request, projectId):
    project = Project.objects.get(id=projectId)

    if request.method == 'POST':
        project.delete()
        return redirect('portfolio:index')

    return render(request, 'project/projDelete.html', {'project': project})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegistrationForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()
            messages.success(request, f'Welcome {username}, your account is now registered')
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {'form': form})

contact/templates/contact/index.html
{% extends 'hobby/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hobbies</title>
</head>
<body>
    {% block body %}
        <p>You can reach me for now at: alexanderklein@mail.weber.edu
        OR message me here:
        </p>
    
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Submit</button>
            </form>
        </div>
    {% endblock %}
</body>
</html>

hobby/templates/hobby/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'hobby/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{%  url 'home:index' %}" class="navbar-brand">Alex Klein</a>
        <div class="navbar">
            <a href="{%  url 'portfolio:index' %}" class="nav-item nav-link">Portfolio</a>
            <a href="{%  url 'hobby:index' %}" class="nav-item nav-link">Hobbies</a>
            <a href="{%  url 'contact:index' %}" class="nav-item nav-link">Contact</a>
            {% if user.is_authenticated %}
                <a href="{%  url 'Logout' %}" class="nav-item nav-link log">Logout</a>
            {% else %}
                <a href="{%  url 'Login' %}" class="nav-item nav-link log">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class='alert alert-{{ message.tags }}'>
                {{ message}}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    
    {% endblock %}
</body>
</html>

hobby/templates/hobby/detail.html
{% extends 'hobby/base.html'%}

{% block body %}
<h1>{{ hobby.hobby_name }}</h1>
<h2>{{ hobby.hobby_desc }}</h2>
<img class="card" height = "150px" src="{{hobby.hobby_img}}">
{% endblock %}

hobby/templates/hobby/index.html
{% extends 'hobby/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hobbies</title>
</head>
<body>
    {% block body %}
    <h1>Hobbies:</h1>
        {% for hobby in hobbyList %}
        <ul>
            <li>
                <div class="row">
                    <div class="col-md-5">
                        <h2>{{hobby.hobby_name }}</h2>
                    </div>
                    <div class="col-md-1">
                        <a href="{%  url 'hobby:detail' hobby.id %}" class="btn btn-success">Details</a>
                    </div>
                </div>
            </li>
        </ul>

        {% endfor %}
    {% endblock %}
</body>
</html>

home/templates/home/index.html
{% extends 'hobby/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hobbies</title>
</head>
<body>
    {% block body %}
        <p>{{aboutMe}}</p>
    {% endblock %}
</body>
</html>

portfolio/templates/project/detail.html
{% extends 'hobby/base.html'%}

{% block body %}
<h1>{{ project.proj_name }}</h1>
<h2>{{ project.proj_desc }}</h2>
<img class="card" height = "150px" src="{{project.proj_img}}">
{% endblock %}

portfolio/templates/project/index.html
{% extends 'hobby/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hobbies</title>
</head>
<body>
    {% block body %}
    <h1>Portfolio:</h1>
        {% for proj in projList %}
        <ul>
            <li>
                <div class="row">
                    <div class="col-md-5">
                        <h2>{{ proj.proj_name }}</h2>
                    </div>
                    <div class="col-md-1">
                        <a href="{%  url 'portfolio:detail' proj.id %}" class="btn btn-success">Details</a>
                    </div>
                </div>
            </li>
        </ul>

        {% endfor %}
    {% endblock %}
</body>
</html>

portfolio/templates/project/projDelete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ project.proj_name }}</h2>
    <button type="submit">Confirm</button>
</form>

portfolio/templates/project/projForm.html
{% extends 'hobby/base.html'%}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'hobby/base.html' %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

users/templates/users/logout.html
{% extends 'hobby/base.html' %}

{% block body %}
    <h1>You have been logged out!</h1>
{% endblock %}

users/templates/users/register.html
{% extends 'hobby/base.html' %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock %}